variables:
  CI_BUILD_NUMBER: $(Build.BuildId)
  BRANCH_NAME: $(Build.SourceBranchName)
  TAG_NAME: $(Build.SourceBranchName)
  YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.yarn

trigger:
  - master
  - ci-*
  - refs/tags/v*

pr:
  branches:
    include:
      - master

stages:
  - stage: Build_Test
    jobs:
      - template: jobs/build_and_test.yml

  - stage: Deploy
    dependsOn:
      - Build_Test
    condition: and( succeeded(), startsWith( variables['Build.SourceBranch'], 'refs/tags' ) )
    jobs:
      - template: jobs/deploy_only_custom.yml

  - stage: Deploy_Docs
    dependsOn:
      - Build_Test
    condition: and( succeeded(), startsWith( variables['Build.SourceBranch'], 'refs/tags' ) )
    jobs:
      - template: jobs/deploy_docs.yml

  - stage: Demo_local_Feed
    dependsOn:
      - Build_Test
    jobs:
      - template: jobs/demo_local_feed.yml

  - stage: Demo_from_Feed
    dependsOn: []
    jobs:
      - template: jobs/demo_from_feed.yml
