variables:
  CI_BUILD_NUMBER: $(Build.BuildId)
  BRANCH_NAME: $(Build.SourceBranchName)
  TAG_NAME: $(Build.SourceBranchName)

trigger:
  - master
  - ci-*
  - refs/tags/v*

pr:
  branches:
    include:
      - master

stages:
  - stage: Build_Test
    jobs:
      - template: jobs/build_and_test.yml

  - stage: Deploy
    dependsOn:
      - Build_Test
    condition: and( succeeded(), startsWith( variables['Build.SourceBranch'], 'refs/tags' ) )
    jobs:
      - template: jobs/deploy_only_custom.yml

  - stage: Demo
    dependsOn: []
    jobs:
      - template: jobs/demo.yml
