jobs:
  - job: build_and_test
    displayName: Build and Test
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
      - bash: yarn install

      - bash: yarn run build

      - bash: yarn run lint

      - bash: yarn run test-results
      
      - task: PublishTestResults@2
        inputs:
          testRunner: JUnit
          testResultsFiles: './tests/*.xml'

      - task: CopyFiles@2
        inputs:
          contents: |
            ./lib/*.js
            ./lib/*.d.ts
            ./package.json
            ./Readme.md
          targetFolder: $(Build.ArtifactStagingDirectory)

      - task: PublishPipelineArtifact@1
        condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
        inputs:
          targetPath: $(Build.ArtifactStagingDirectory)
          artifactName: drop
