jobs:
  - job: build_and_test
    displayName: build and test
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
      - bash: yarn install
        displayName: install node modules

      - bash: yarn run build
        displayName: build

      - bash: yarn run lint
        displayName: lint

      - bash: |
          yarn run test-results
        displayName: test

      - bash: |
          yarn run test-coverage
        displayName: test (coverage)
        condition: always()
      
      - task: PublishTestResults@2
        condition: always()
        inputs:
          testRunner: JUnit
          testResultsFiles: 'out/tests/test-results.xml'

      - task: CopyFiles@2
        condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
        inputs:
          contents: |
            lib/*.js
            lib/*.d.ts
            package.json
            Readme.md
          targetFolder: $(Build.ArtifactStagingDirectory)

      - task: PublishPipelineArtifact@1
        condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
        inputs:
          targetPath: $(Build.ArtifactStagingDirectory)
          artifactName: drop
