jobs:
  - job: demo_from_feed
    displayName: demo with package from feed
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
      - bash: |
            cd demo/from-feed
            echo "switched to demo/from-feed subfolder"
            echo "------------------------------------------------------"
            yarn install
            echo "------------------------------------------------------"
            yarn run build
            echo "------------------------------------------------------"
            node dist/app.js
            echo "------------------------------------------------------"
            echo "done"
        displayName: demo for consumer of published package
