jobs:
  - job: demo
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
      - bash: |
            cd demo
            echo "switched to demo subfolder"
            echo "------------------------------------------------------"
            yarn install
            echo "------------------------------------------------------"
            yarn run build
            echo "------------------------------------------------------"
            node dist/app.js
            echo "------------------------------------------------------"
            echo "done"
        displayName: demo for consumer of published package
