jobs:
  - job: deploy_package
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
      - checkout: none

      - download: current
        artifact: tarball

      - task: ExtractFiles@1
        inputs:
          archiveFilePatterns: '$(Pipeline.Workspace)/tarball/package.tgz'
          destinationFolder: './tmp'
          cleanDestinationFolder: false

      - bash: |
          ls -la tmp/package
          echo ""

          if [[ "$TAG_NAME" =~ ^v([0-9]+)\.([0-9]+)\.([0-9]+)(-(preview-[0-9]+))$ ]]; then
              mkdir deploy_custom
              mv tmp/package/* deploy_custom

              # update version in package.json -- cut off the v-prefix in the TAG_NAME
              cd deploy_custom
              yarn version --new-version ${TAG_NAME#v}
              cd -

              echo "##vso[task.setvariable variable=deploy_custom;]1"
          elif [[ "$TAG_NAME" =~ ^v([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
              mkdir deploy_npm
              mv tmp/package/* deploy_npm

              # update version in package.json -- cut off the v-prefix in the TAG_NAME
              cd deploy_npm
              yarn version --new-version ${TAG_NAME#v}
              cd -

              echo "##vso[task.setvariable variable=deploy_npm;]1"
          else
              echo "no deploy, as '$TAG_NAME' does not match"
              echo "##vso[task.complete result=SucceededWithIssues;]tag does not match for deploy"
          fi

          echo "-------------------------------------------------"
          echo "custom:"
          ls -la deploy_custom
          echo "-------------------------------------------------"
          echo "npm:"
          ls -la deploy_npm
          echo "-------------------------------------------------"
        displayName: deploy to npm or local feed

      - task: Npm@1
        condition: eq(variables['deploy_custom'], '1')
        inputs:
          command: publish
          workingDir: deploy_custom
          publishRegistry: useFeed
          publishFeed: 'AzureDevOpsTest/gfoidl-tests'
        displayName: deploy to custom feed

      - task: Npm@1
        condition: eq(variables['deploy_npm'], '1')
        inputs:
          command: publish
          workingDir: deploy_npm
          publishEndpoint: npm      # service connection defined in Azure DevOps UI
        displayName: deploy to npm
