version: 2
defaults: &defaults
    working_directory: ~/repo
    docker:
        - image: circleci/node:7.10
jobs:
    build:
        <<: *defaults
        steps:
            - checkout
            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "package.json" }}
                    - v1-dependencies-
            - run: yarn install
            - save_cache:
                key: v1-dependencies-{{ checksum "package.json" }}
                paths:
                    - node_modules
            - run: yarn run build
            - run: yarn run lint
            - persist_to_workspace:
                root: .
                paths:
                    - ./*
    test:
        <<: *defaults
        steps:
            - attach_workspace:
                at: .
            - run: yarn run test
    deploy:
        <<: *defaults
        steps:
            - attach_workspace:
                at: .
            - run: echo -e "$NPM_USER\n$NPM_PASSWORD\n$NPM_EMAIL" | npm login
            - run: npm publish
workflows:
    version: 2
    build_and_test:
        jobs:
            - build:
                filters:
                    tags:
                        only: /.*/
            - test:
                requires:
                    - build
                filters:
                    tags:
                        only: /.*/
            - deploy:
                requires:
                    - test
                filters:
                    branches:
                        ignore: /.*/
                    tags:
                        only: /^v[0-9]\.[0-9]\.[0-9]$/